FROM ubuntu:20.04 
MAINTAINER Sergio Sánchez "codExcute@example.com" 
RUN apt-get update
RUN apt-get install -y nginx
RUN apt-get install -y php-fpm
COPY /home/ubuntu/loginV4 /usr/share/nginx/html/
ENTRYPOINT ["/usr/sbin/nginx","-g","daemon off;"]
EXPOSE 80

